services:
  inventoryservice:
    restart: "no"
  orderservice:
    restart: "no"
    command:
      - --config
      - /app/config/config.yaml
      - --values
      - /app/config/overrides.yaml
      - --overrides
      - /scenario/orderservice.overrides.yaml
    volumes:
      - ${SERVICELIB_SCENARIO_ARTIFACTS_DIR}/typescript:/scenario:ro
    depends_on: [inventoryservice]
