services:
  inventoryservice:
    entrypoint:
      - python
      - -OO
      - /benchmark/python_entrypoint.py
      - inventory_service.main
    command:
      - --config
      - /workspace/config/config.yaml
      - --overrides
      - /benchmark-config/inventoryservice.overrides.yaml
    environment:
      PYTHONHASHSEED: "0"
      PYTHONOPTIMIZE: "2"
    volumes:
      - ${BENCHMARK_DIR}/python_entrypoint.py:/benchmark/python_entrypoint.py:ro
      - ${BENCHMARK_PYTHON_CONFIG_DIR}:/benchmark-config:ro

  orderservice:
    entrypoint:
      - python
      - -OO
      - /benchmark/python_entrypoint.py
      - order_service.main
    command:
      - --config
      - /workspace/config/config.yaml
      - --overrides
      - /benchmark-config/orderservice.overrides.yaml
    environment:
      PYTHONHASHSEED: "0"
      PYTHONOPTIMIZE: "2"
    volumes:
      - ${BENCHMARK_DIR}/python_entrypoint.py:/benchmark/python_entrypoint.py:ro
      - ${BENCHMARK_PYTHON_CONFIG_DIR}:/benchmark-config:ro
