services:
  orderservice:
    cpus: ${BENCHMARK_SERVICE_CORES}
    environment:
      BENCHMARK_DURATION_SECONDS: ${BENCHMARK_DURATION_SECONDS}
      BENCHMARK_VUS: ${BENCHMARK_VUS}
      DEFAULT_POOL_EXECUTORS_COUNT: ${BENCHMARK_SERVICE_CORES}
      ORDER_PROCESSED_ENABLED: "false"
      SERVICELIB_NOOP_LOGS: "1"
      SERVICELIB_NOOP_METRICS: "1"
      SERVICELIB_NOOP_TRACING: "1"
    ports: !reset []
    restart: "no"
