services:
  jaeger:
    image: jaegertracing/all-in-one:1.62.0
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686"
    networks: [app_net]

  analyticsservice:
    environment:
      ANALYTICS_SERVICE_ENVIRONMENT: production
      ORDER_EVENTS_BROKERS: redpanda:9092
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
    depends_on:
      - otel-collector

  inventoryservice:
    environment:
      INVENTORY_SERVICE_ENVIRONMENT: production
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
    depends_on:
      - otel-collector

  orderservice:
    environment:
      ORDER_SERVICE_ENVIRONMENT: production
      ORDER_EVENTS_BROKERS: redpanda:9092
      ORDER_PROCESSED_ENABLED: "true"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
    depends_on:
      - inventoryservice
      - otel-collector
