services:
  analyticsservice:
    environment:
      ANALYTICS_SERVICE_ENVIRONMENT: debug
      ORDER_EVENTS_BROKERS: redpanda:9092
      RUST_LOG: info

  inventoryservice:
    environment:
      INVENTORY_SERVICE_ENVIRONMENT: debug
      RUST_LOG: info

  orderservice:
    environment:
      ORDER_SERVICE_ENVIRONMENT: debug
      RUST_LOG: info
      ORDER_PROCESSED_ENABLED: "true"
    depends_on:
      - inventoryservice
